TaskManagementOsvin/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TaskManagementOsvin.Models
{
    public class Department
    {
        public long DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}

TaskManagementOsvin/Controllers/ManagementController.cs
using DomainModel.EntityModel;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using Newtonsoft.Json;
using Providers.Helper;
using Providers.Providers.SP.Repositories;
using Providers.Repositories;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.UI;
using TaskManagementOsvin.Models;
using TaskManagementOsvin.Security;

namespace TaskManagementOsvin.Controllers
{
    [Authorize]
    public class ManagementController : Controller
    {
        string BaseURL = ConfigurationManager.AppSettings["BaseURL"];
        static readonly IManagement managementRepository = new ManagementRepository();
        [HttpGet]
        public ActionResult AddEmployee(int UserId = 0)
        {
            EmployeeModel employee = new EmployeeModel();
            if (UserId > 0)
            {
                var client = new HttpClient();
                client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
                var result = client.GetAsync(BaseURL + "/api/Management/GetEmployeeDataById?UserId=" + UserId).Result;
                if (result.StatusCode == HttpStatusCode.OK)
                {
                    var contents = result.Content.ReadAsStringAsync().Result;
                    var Response = new JavaScriptSerializer().Deserialize<EmployeeModel>(contents);
                    employee = Response;
                    employee.DOB = employee.DateOfBirth.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture);
                }
            }
            employee.listDepartment = GetDepartments();
            employee.listDepartment = employee.listDepartment.Where(s => s.IsActive == true).ToList();
            var list = new List<SelectListItem>
            {
                new SelectListItem{ Text="Admin", Value = "Admin"},
                new SelectListItem{ Text="HR", Value = "HR"},
                new SelectListItem{ Text="Project Manager", Value = "Project Manager"},
                new SelectListItem{ Text="Network Admin", Value = "Network Admin"},
                new SelectListItem{ Text="Team Leader", Value = "Team Leader"},
                new SelectListItem {Text="Employee", Value="Employee" }
            };
            if (employee.DepartmentId > 0)
            {
                employee.listDesignation = GetDesignations(employee.DepartmentId);
            }
            ViewData["ddlRole"] = list;
            ViewBag.Class = "display-hide";
            return View(employee);
        }
        [HttpPost]
        public ActionResult AddEmployee(EmployeeModel model)
        {
            ViewBag.Class = "display-hide";
            try
            {
                if (ModelState.IsValid)
                {
                    model.CreatedBy = UserManager.user.UserId;
                    model.Archived = "NonArchive";
                    string path = Server.MapPath("~/UploadDocuments/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    if (model.ImageFile != null)
                    {
                        string Imagepath = Server.MapPath("~/Images/UserImages/");
                        if (!Directory.Exists(Imagepath))
                        {
                            Directory.CreateDirectory(Imagepath);
                        }
                        string fileName = Path.GetFileName(model.ImageFile.FileName);
                        fileName = "test" + Guid.NewGuid().ToString() + Path.GetExtension(model.ImageFile.FileName);
                        model.ImageFile.SaveAs(Imagepath + fileName);
                        model.Image = fileName;
                        model.ImageFile = null;
                    }
                    if (model.IDCardFirst_File != null)
                    {
                        string fileName = Path.GetFileName(model.IDCardFirst_File.FileName);
                        fileName = "test" + Guid.NewGuid().ToString() + Path.GetExtension(model.IDCardFirst_File.FileName);
                        model.IDCardFirst_File.SaveAs(path + fileName);
                        model.IDCardFirst = fileName;
                        model.IDCardFirst_File = null;
                    }
                    if (model.IDCardSecond_AddressProof_File != null)
                    {
                        string fileName = Path.GetFileName(model.IDCardSecond_AddressProof_File.FileName);
                        fileName = "test" + Guid.NewGuid().ToString() + Path.GetExtension(model.IDCardSecond_AddressProof_File.FileName);
                        model.IDCardSecond_AddressProof_File.SaveAs(path + fileName);
                        model.IDCardSecond_AddressProof_ = fileName;
                        model.IDCardSecond_AddressProof_File = null;
                    }
                    if (model.CV_File != null)
                    {
                        string fileName = Path.GetFileName(model.CV_File.FileName);
                        fileName = "test" + Guid.NewGuid().ToString() + Path.GetExtension(model.CV_File.FileName);
                        model.CV_File.SaveAs(path + fileName);
                        model.CV = fileName;
                        model.CV_File = null;
                    }
                    if (model.ExperienceCertificate_File != null)
                    {
                        string fileName = Path.GetFileName(model.ExperienceCertificate_File.FileName);
                        fileName = "test" + Guid.NewGuid().ToString() + Path.GetExtension(model.ExperienceCertificate_File.FileName);
                        model.ExperienceCertificate_File.SaveAs(path + fileName);
                        model.ExperienceCertificate = fileName;
                        model.ExperienceCertificate_File = null;
                    }
                    if (model.AppointementLetter_File != null)
                    {
                        string fileName = Path.GetFileName(model.AppointementLetter_File.FileName);
                        fileName = "test" + Guid.NewGuid().ToString() + Path.GetExtension(model.AppointementLetter_File.FileName);
                        model.AppointementLetter_File.SaveAs(path + fileName);
                        model.AppointementLetter = fileName;
                        model.AppointementLetter_File = null;
                    }
                    if (model.AggrementDocument_File != null)
                    {
                        string fileName = Path.GetFileName(model.AggrementDocument_File.FileName);
                        fileName = "test" + Guid.NewGuid().ToString() + Path.GetExtension(model.AggrementDocument_File.FileName);
                        model.AggrementDocument_File.SaveAs(path + fileName);
                        model.AggrementDocument = fileName;
                        model.AggrementDocument_File = null;
                    }
                    if (model.OtherDocument_File != null)
                    {
                        string fileName = Path.GetFileName(model.OtherDocument_File.FileName);
                        fileName = "test" + Guid.NewGuid().ToString() + Path.GetExtension(model.OtherDocument_File.FileName);
                        model.OtherDocument_File.SaveAs(path + fileName);
                        model.OtherDocument = fileName;
                        model.OtherDocument_File = null;
                    }
                    if (!string.IsNullOrWhiteSpace(model.DOB))
                        model.DateOfBirth = DateTime.ParseExact(model.DOB, "dd/MM/yyyy", null);
                    //model.DateOfBirth = Convert.ToDateTime(model.DOB);
                    var serialized = JsonConvert.SerializeObject(model);
                    var client = new HttpClient();
                    var content = new StringContent(serialized, System.Text.Encoding.UTF8, "application/json");
                    client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
                    var result = client.PostAsync(BaseURL + "/api/Management/AddUpdateEmployee", content).Result;
                    if (result.StatusCode == HttpStatusCode.OK)
                    {
                        var contents = result.Content.ReadAsStringAsync().Result;
                        var Response = JsonConvert.DeserializeObject<ResponseModel>(contents);
                        ModelState.Clear();
                        ModelState.AddModelError("CustomError", Response.response);
                        ViewBag.Class = "alert-success";
                        model = new EmployeeModel();
                    }
                    else if (result.StatusCode == HttpStatusCode.Unauthorized)
                    {
                        var contents = result.Content.ReadAsStringAsync().Result;
                        var Response = JsonConvert.DeserializeObject<ResponseModel>(contents);
                        ModelState.AddModelError("CustomError", Response.response);
                        ViewBag.Class = "alert-danger";
                    }
                    else
                    {
                        ModelState.AddModelError("CustomError", "Error occurred");
                        ViewBag.Class = "alert-danger";
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("CustomError", ex.Message);
                ViewBag.Class = "alert-danger";
            }
            model.listDepartment = GetDepartments();
            model.listDepartment = model.listDepartment.Where(s => s.IsActive == true).ToList();
            if (model.DepartmentId > 0)
            {

TaskManagementOsvin/Views/Management/AddUpdateUser.cshtml
@using System.Configuration
@{
    ViewBag.Title = "AddUpdateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using TaskManagementOsvin.Security;
@using TaskManagementOsvin.Models;
@model List<EmployeeDomainModel>
<div class="page-content">
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="~/Dashboard/Welcome">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="#">Add/Update User</a>
                <i class="fa fa-circle"></i>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h1 class="page-title">
        Add / Update User
        @*<small>blank page layout</small>*@
    </h1>
    <!-- END PAGE TITLE-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-settings font-green"></i>
                        <span class="caption-subject font-green bold uppercase">User Details</span>
                    </div>
                    @if (UserManager.user.roleType == roleTypeModel.Admin || UserManager.user.roleType == roleTypeModel.HR)
                    {
                        <div class="col-sm-offset-3 col-sm-6">
                            <div class="actions actions-padding">
                                <div class="action-inline">
                                    <label for="ddlArchived" class="control-label">Employee Type</label>
                                    <select id="ddlArchived" class="form-control">
                                        <option value="false" selected>Non Archive</option>
                                        <option value="true">Archive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-sm green table-group-action-submit pull-right" href="~/Management/AddEmployee">
                            <i class="fa fa-plus"></i> Add Employee
                        </a>
                    }
                </div>
                <div class="portlet-body dv_UserTableContainer">                   
                    @Html.Action("_AddUpdateUser", "Management")
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var basehref = '@ConfigurationManager.AppSettings["BaseURL"]';
    jQuery(document).on('ready', function () {
        var table = $('#sample_2').DataTable();
        table.state.clear();
        table.destroy();
        TableDatatablesFixedHeader.init();
        $("#ddlArchived").val('false');
        $(document).on('change', '#ddlArchived', function () {
            var _this = $(this);
            var Archived = _this.val();
            if (typeof Archived != 'undefined') {
                $.ajax({
                    type: "GET",
                    url: basehref + "/Management/_AddUpdateUser?Archived=" + Archived,
                    //data: { sortBy: sortByval },
                    contentType: "application/text; charset=utf-8",
                    dataType: "text",
                    success: function (response) {
                        $('.dv_UserTableContainer').html(response);
                        var table = $('#sample_2').DataTable();
                        table.state.clear();
                        table.destroy();
                        TableDatatablesFixedHeader.init();
                    },
                    failure: function (msg) {
                        html = false;
                    }
                });
            }
        });
    });
    function ArchiveEmployee(UserId) {
        var Archived = $("#ddlArchived").val();
        $.ajax({
            type: "Get",
            contentType: "application/json; charset=utf-8",
            url: basehref + "/Management/ArchiveEmployee?UserId=" + UserId + "&Archived=" + Archived,
            success: function (response) {
                $('.dv_UserTableContainer').html(response);
                TableDatatablesFixedHeader.init();
                if (Archived=="true") {
                    $("#lblMessage").html("User has removed from archive.");
                }
                else {
                    $("#lblMessage").html("User has archived.");
                }
                $(".dvAlert").show();
            },
            error: function (error) {
                $("#lblMessage").html("Something went wrong, please try again.");
                $(".dvAlert").show();
                console.log(error);
            }
        });
    }
    function ActivateDeactivateUser(UserId, IsActive) {
        var Archived = $("#ddlArchived").val();
        $.ajax({
            type: "Get",
            contentType: "application/json; charset=utf-8",
            url: basehref + "/Management/ActivateDeactivateUser?UserId=" + UserId + "&IsActive=" + IsActive + "&Archived=" + Archived,
            success: function (response) {
                $('.dv_UserTableContainer').html(response);
                TableDatatablesFixedHeader.init();
                //if (response.isSuccess == true) {
                //    if (IsActive == false) {
                //        $("#StatusActiveLink_" + UserId).remove();
                //        $("#StatusActive_" + UserId).append('<a id="StatusActiveLink_' + UserId + '" href="#" onclick="ActivateDeactivateUser(' + UserId + ', true)"><img alt="In Active" src="/assets/global/img/Guiimages/InActive.png" width="30px" height="30px"/></a>');
                //    }
                //    else {
                //        $("#StatusActiveLink_" + UserId).remove();
                //        $("#StatusActive_" + UserId).append('<a id="StatusActiveLink_' + UserId + '" href="#" onclick="ActivateDeactivateUser(' + UserId + ', false)"><img alt="Active" src="/assets/global/img/Guiimages/Active.png" width="30px" height="30px"/></a>');
                //    }
                //}
            },
            error: function (error) {
                console.log(error);
            }
        });
    }
    function DeleteUser(param) {
        $(".dvAlert").hide();
        $("#lblMessage").html("");
        var UserId = param;
        $.ajax({
            type: "Get",
            contentType: "application/json; charset=utf-8",
            url: basehref + "/api/Management/DeleteUserById?UserId=" + UserId,
            beforeSend: function () {
                $(".lblMessage").html("Please wait...");
                $(".dvAlert").show();
            },
            success: function (response) {
                if (response.isSuccess == true) {
                    $("#row_" + UserId).remove();
                    $("#lblMessage").html("User deleted successfully");
                    $(".dvAlert").show();
                }
                else {
                    $("#lblMessage").html(response.response);
                    $(".dvAlert").show();
                }
            },
            error: function (error) {
                $("#lblMessage").html("Something went wrong, please try again");
                $(".dvAlert").show();
                console.log(error);
            }
        });
    }
</script>

TaskManagementOsvin/Views/Management/Departments.cshtml
@{
    ViewBag.Title = "Departments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content">
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="~/Dashboard/Welcome">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="#">Departments</a>
                <i class="fa fa-circle"></i>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h1 class="page-title">
        Add / Update Departments
        @*<small>blank page layout</small>*@
    </h1>
    <!-- END PAGE TITLE-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-layers font-green"></i>
                        <span class="caption-subject font-green bold uppercase">Department Details</span>
                    </div>
                    <a class="btn btn-sm green table-group-action-submit pull-right" href="#" id="btnAddDepartment">
                        <i class="fa fa-plus"></i> Add Department
                    </a>
                </div>
                <div class="portlet-body">
                    <div class="alert alert-success dvAlert @ViewBag.Class">
                        @*<button type="button" class="close" data-close="alert"></button>*@
                        <a class="close" onclick="$('.alert').hide()">×</a>
                        <span id="lblMessage"> @ViewBag.Message </span>
                    </div>
                    <div class="row" id="dvAddDept" style="display:none">
                        <div class="col-md-12">
                            @using (Html.BeginForm("AddDepartment", "Management", FormMethod.Post, new { enctype = "multipart/form-data", @id = "frmChangePassword", @class = "form-horizontal" }))
                            {
                                <div class="form-body">
                                    @*<div class="text-danger">
                                            <label id="lblmsg"></label>
                                        </div>*@
                                    <div class="form-group">
                                        <input type="hidden" id="hdnDeptId" />
                                        <label class="control-label col-md-4">
                                            Department Name
                                            <span class="required"> * </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input tye="text" class="form-control" id="txtDepartmentName" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="text-center">
                                            <button type="button" class="btn green" id="btnAdd">Add</button>
                                            <button type="button" class="btn green" id="btnUpdate" style="display:none">Update</button>
                                            <button type="button" class="btn red" id="btnCancel">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="row" id="dvDepartmentDetails">
                        @Html.Action("_Departments", "Management")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--AddUpdate modal -->
<script type="text/javascript">
    jQuery(document).on('ready', function () {
        var table = $('#sample_2').DataTable();
        table.state.clear();
        table.destroy();
        TableDatatablesFixedHeader.init();       
    });
    function DeleteDepartment(param) {
        $(".dvAlert").hide();
        $("#lblMessage").html("");
        var DepartmentId = param;
        $.ajax({
            type: "Get",
            contentType: "application/json; charset=utf-8",
            url: "/Management/DeleteDepartmentById?DepartmentId=" + DepartmentId,
            beforeSend: function () {
                $("#lblMessage").html("Please wait...");
                $(".dvAlert").show();
            },
            success: function (response) {
                $('#dvDepartmentDetails').html(response);
                TableDatatablesFixedHeader.init();
                $("#lblMessage").html("Department deleted successfully");
                $(".dvAlert").show();
            },
            error: function (error) {
                $("#lblMessage").html("Something went wrong, please try again");
                $(".dvAlert").show();
                console.log(error);
            }
        });
    }

    function ActivateDeactivateDepartment(DepartmentId, IsActive) {
        $(".dvAlert").hide();
        $("#lblMessage").html("");
        $.ajax({
            type: "Get",
            contentType: "application/json; charset=utf-8",
            url: "/Management/ActivateDeactivateDepartment?DepartmentId=" + DepartmentId + "&IsActive=" + IsActive,
            success: function (response) {
                $('#dvDepartmentDetails').html(response);
                TableDatatablesFixedHeader.init();
            },
            error: function (error) {
                console.log(error);
            }
        });
    }
    $("#btnAdd").click(function () {
        $("#lblMessage").html("");
        $(".dvAlert").hide();
        var IsValid = true;
        var DepartmentName = $("#txtDepartmentName").val()
        if (DepartmentName == null || DepartmentName == "") {
            $('#txtDepartmentName').css('border-color', 'red');
            IsValid = false;
        }
        else {
            $('#txtDepartmentName').css('border-color', '');
        }
        if (IsValid == false) {
            return false;
        }
        var model = {
            DepartmentName: DepartmentName
        }
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            url: "/Management/AddUpdateDepartment",
            data: JSON.stringify(model),
            beforeSend: function () {
                $("#lblMessage").html("Please wait...");
                $(".dvAlert").show();
            },
            success: function (response) {
                $('#dvDepartmentDetails').html(response);
                TableDatatablesFixedHeader.init();
                $("#lblMessage").html("Department added successfully");
                $(".dvAlert").show();
                $("#txtDepartmentName").val('');
            },
            error: function (error) {
                $("#lblMessage").html("Something went wrong, please try again");
                $(".dvAlert").show();
                console.log(error);
            }
        });
    });
    function EditDepartment(DepartmentId, DepartmentName) {
        $("#lblMessage").html("");
        $(".dvAlert").hide();
        $("#dvAddDept").show();
        $("#hdnDeptId").val(DepartmentId);
        $("#txtDepartmentName").val(DepartmentName);
        $("#btnAdd").hide();
        $("#btnUpdate").show();
    }
    $("#btnUpdate").click(function () {
        $("#lblMessage").html("");
        $(".dvAlert").hide();
        var DepartmentName = $("#txtDepartmentName").val();
        var IsValid = true;
        if (DepartmentName == null || DepartmentName == "") {
            $('#txtDepartmentName').css('border-color', 'red');
            IsValid = false;
        }
        else {
            $('#txtDepartmentName').css('border-color', '');
        }
        if (IsValid == false) {
            return false;
        }
        var model = {
            DepartmentId: $("#hdnDeptId").val(),
            DepartmentName: DepartmentName
        }
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            url: "/Management/AddupdateDepartment",
            data: JSON.stringify(model),
            beforeSend: function () {
                $("#lblMessage").html("Please wait...");
                $(".dvAlert").show();
            },
            success: function (response) {
                $('#dvDepartmentDetails').html(response);
                TableDatatablesFixedHeader.init();
                $("#lblMessage").html("Department updated successfully");
                $(".dvAlert").show();
                $("#btnUpdate").hide();
                $("#btnAdd").show();
                $("#txtDepartmentName").val('');
            },
            error: function (error) {
                $("#lblMessage").html("Something went wrong, please try again");
                $(".dvAlert").show();
                console.log(error);
            }
        });
    });
    $("#btnAddDepartment").click(function () {
        $("#dvAddDept").show();
        $("#btnAdd").show();
        $("#btnUpdate").hide();
    });
    $("#btnCancel").click(function () {
        $("#dvAddDept").hide();
        $("#txtDepartmentName").val('');
    });
</script>

TaskManagementOsvin/Views/Management/PaySlip.cshtml
@{
    ViewBag.Title = "PaySlip";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model TaskManagementOsvin.Models.PaySlipModel
<div class="page-content">
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="~/Dashboard/Welcome">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="#">Employee Salary Slip</a>
                <i class="fa fa-circle"></i>
            </li>
            @*<li>
                    <span>Page Layouts</span>
                </li>*@
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right">
                <button type="button" class="btn green btn-sm btn-outline dropdown-toggle" data-toggle="dropdown">
                    Actions
                    <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li>
                        <a href="#">
                            <i class="icon-bell"></i> Action
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="icon-shield"></i> Another action
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="icon-user"></i> Something else here
                        </a>
                    </li>
                    <li class="divider"> </li>
                    <li>
                        <a href="#">
                            <i class="icon-bag"></i> Separated link
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END PAGE BAR -->
    <h1 class="page-title">
        Employee Salary Slip
        <small></small>
    </h1>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-layers font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">Employee Salary Slip</span>
                    </div>
                </div>
                <div class="portlet-body form">
                    @{ Html.RenderPartial("_PaySlip", Model);}
                </div>
                <div class="form-actions text-center">
                    <div class="btn-set">
                        <a href="~/Management/GenerateSalarySlip?UserId=235" class="btn green">Edit</a>
                        <a href="~/Management/EmailPaySlipToEmployee" class="btn red">Send Mail To Employee</a>
                        <a href="~/Management/GeneratePaySlipPdf" class="btn purple">Generate PDF</a>
                        <a href="~/Management/GenerateSalarySlip" class="btn blue">New Salary Slip</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- END VALIDATION STATES-->
    </div>

</div>