TaskManagementOsvin/Controllers/BugsController.cs
using Newtonsoft.Json;
using Providers.Helper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TaskManagementOsvin.Models;
using TaskManagementOsvin.Security;
using DomainModel.EntityModel;
using System.Configuration;

namespace TaskManagementOsvin.Controllers
{
    [Authorize]
    public class BugsController : Controller
    {
        string BaseURL = ConfigurationManager.AppSettings["BaseURL"];
        // GET: Bugs
        public ActionResult ReportBug(long BugId = 0)
        {
            var client = new HttpClient();
            BugsModel model = new BugsModel();
            if (BugId > 0)
            {
                model.BugId = BugId;
                model.Mode = "Edit";
                model.UserId = 0;
                model.ProjectId = 0;
                var serialized = JsonConvert.SerializeObject(model);
                var content = new StringContent(serialized, System.Text.Encoding.UTF8, "application/json");
                client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
                var result = client.PostAsync(BaseURL + "/api/Bugs/GetBugDetails", content).Result;
                if (result.StatusCode == HttpStatusCode.OK)
                {
                    var contents = result.Content.ReadAsStringAsync().Result;
                    var Response = JsonConvert.DeserializeObject<List<BugsModel>>(contents);
                    if (Response.Count > 0)
                        model = Response.FirstOrDefault();
                }
            }
            client = new HttpClient();
            client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
            var Clientresult = client.GetAsync(BaseURL + "/api/Bugs/GetEmployees").Result;
            if (Clientresult.StatusCode == HttpStatusCode.OK)
            {
                var contents = Clientresult.Content.ReadAsStringAsync().Result;
                var response = new JavaScriptSerializer().Deserialize<List<EmployeesDomainModel>>(contents);
                model.listEmployees = response;
            }
            var ClientResult1 = client.GetAsync(BaseURL + "/api/Project/GetProjectList").Result;
            if (ClientResult1.StatusCode == HttpStatusCode.OK)
            {
                var contents = ClientResult1.Content.ReadAsStringAsync().Result;
                var response = new JavaScriptSerializer().Deserialize<List<ProjectDomainModel>>(contents);
                model.listProjects = response;
            }
            var listPriority = new List<SelectListItem>
            {
                new SelectListItem{ Text="High", Value = "High"},
                new SelectListItem{ Text="Low", Value = "Low"},
                new SelectListItem{ Text="Urgent", Value = "Urgent"},
                new SelectListItem {Text="Immediate", Value="Immediate" }
            };
            var listStatus = new List<SelectListItem>
            {
                new SelectListItem{ Text="New", Value = "New"},
                new SelectListItem{ Text="ReOpened", Value = "ReOpened"},
                new SelectListItem {Text="Closed", Value="Closed" }
            };
            ViewData["ddlPriority"] = listPriority;
            ViewData["ddlStatus"] = listStatus;
            ViewBag.Class = "display-hide";
            return View(model);
        }
        [HttpPost]
        public ActionResult ReportBug(BugsModel model)
        {
            ViewBag.Class = "display-hide";
            var client = new HttpClient();
            try
            {
                if (ModelState.IsValid)
                {
                    model.Files = "";
                    model.BugReportedBy = UserManager.user.UserId;
                    HttpPostedFileBase[] PostedFiles = model.PostedFiles;
                    model.PostedFiles = null;
                    var serialized = JsonConvert.SerializeObject(model);
                    var content = new StringContent(serialized, System.Text.Encoding.UTF8, "application/json");
                    client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
                    var result = client.PostAsync(BaseURL + "/api/Bugs/AddUpdateBug", content).Result;
                    if (result.StatusCode == HttpStatusCode.OK)
                    {
                        var contents = result.Content.ReadAsStringAsync().Result;
                        var Response = JsonConvert.DeserializeObject<ResponseModel>(contents);
                        if (Response.isSuccess == true)
                        {
                            if (Response.response == "Bug added successfully.")
                            {
                                //String Email = GetUserEmail(model.UserId);                                
                                ////Session["Email1"] = Email;
                                ////Session["ProjectName"] = model.ProjectId;
                                ////Session["Bugsubject"] = model.BugSubject;
                                //Thread threadSendMails;

                                //threadSendMails = new Thread(delegate ()
                                //{
                                //    //SendEmail(Session["Email1"].ToString(), Session["ProjectName"].ToString(), Session["Bugsubject"].ToString());
                                //    SendEmail(Email, GetProjectTitle(model.ProjectId), model.BugSubject.ToString());

                                //});
                                //threadSendMails.IsBackground = true;

                                //threadSendMails.Start();

                                string insertfile = string.Empty;
                                foreach (HttpPostedFileBase file in PostedFiles)
                                {
                                    if (file != null)
                                    {
                                        Guid g1 = Guid.NewGuid();
                                        string ext = System.IO.Path.GetExtension(file.FileName);
                                        string fileName = g1 + ext;
                                        var ServerSavePath = Path.Combine(Server.MapPath("~/BugUploadDocument/") + fileName);
                                        file.SaveAs(ServerSavePath);
                                        insertfile = AddBugFiles(fileName);
                                    }
                                }
                                if (insertfile != null)
                                {
                                    if (insertfile == "InsertImage")
                                    {
                                       
                                    }
                                }
                                ModelState.Clear();
                                ModelState.AddModelError("CustomError", Response.response);
                                ViewBag.Class = "alert-success";
                                model = new BugsModel();
                            }
                            else if (Response.response == "Bug updated successfully.")
                            {
                                //if (model.Status == "ReOpened")
                                //{
                                //    String Email = GetUserEmail(model.UserId);
                                //    //Session["Email1"] = Email;
                                //    //Session["ProjectName"] = model.ProjectId;
                                //    //Session["Bugsubject"] = Convert.ToString(model.BugSubject);
                                //    Thread threadSendMails;

                                //    threadSendMails = new Thread(delegate ()
                                //    {
                                //        //SendEmail(Session["Email1"].ToString(), Session["ProjectName"].ToString(), Session["Bugsubject"].ToString());
                                //        SendEmail(Email, GetProjectTitle(model.ProjectId), model.BugSubject);
                                //    });
                                //    threadSendMails.IsBackground = true;

                                //    threadSendMails.Start();
                                //}
                                string updatefile = string.Empty;
                                foreach (HttpPostedFileBase file in PostedFiles)
                                {
                                    if (file != null)
                                    {
                                        Guid g1 = Guid.NewGuid();
                                        string ext = System.IO.Path.GetExtension(file.FileName);
                                        string fileName = g1 + ext;
                                        var ServerSavePath = Path.Combine(Server.MapPath("~/BugUploadDocument/") + fileName);
                                        file.SaveAs(ServerSavePath);
                                        updatefile = UpdateBugFiles(model.BugId, fileName);
                                    }
                                }
                                if (updatefile != null)
                                {
                                    if (updatefile == "UpdateImage")
                                    {
                                       
                                    }
                                }
                                ModelState.Clear();
                                ModelState.AddModelError("CustomError", Response.response);
                                ViewBag.Class = "alert-success";
                                model = new BugsModel();
                            }
                        }
                    }
                    else if (result.StatusCode == HttpStatusCode.Unauthorized)

TaskManagementOsvin/Views/Bugs/BugsList.cshtml
@{
    ViewBag.Title = "BugsList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using TaskManagementOsvin.Security;
@using TaskManagementOsvin.Models;
<div class="page-content">
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="~/Dashboard/Welcome">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="~/EmployeeDailyStatusReport/EmployeeReport">Bugs List</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="#">Employee Reporting</a>
                <i class="fa fa-circle"></i>
            </li>
            @*<li>
                    <span>Page Layouts</span>
                </li>*@
        </ul>
       
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h1 class="page-title">
        Bugs List
        @*<small>blank page layout</small>*@
    </h1>
    <!-- END PAGE TITLE-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-settings font-green"></i>
                        <span class="caption-subject font-green bold uppercase">Bugs</span>
                    </div>
                    <div class="col-md-12 form-group">
                        @if (UserManager.user.roleType == roleTypeModel.Admin || UserManager.user.roleType == roleTypeModel.HR || UserManager.user.roleType == roleTypeModel.ProjectManager)
                        {
                            <div class="col-md-offset-3 col-md-3">
                                <label class="control-label">Employee</label>
                                @Html.DropDownList("ddlEmployee", ViewBag.listEmployees as SelectList, "Select Employee", new { @class = "form-control" })
                            </div>
                            <div class="col-md-3">
                                <label class="control-label">Project</label>
                                @Html.DropDownList("ddlProject", ViewBag.listProjects as SelectList, "Select Project", new { @class = "form-control" })
                            </div>
                        }
                        else
                        {
                            <div class="col-md-offset-3 col-md-3">
                                <label class="control-label">Project</label>
                                @Html.DropDownList("ddlProject", ViewBag.listProjects as SelectList, "Select Project", new { @class = "form-control" })
                            </div>
                        }
                    </div>
                    <div class="col-md-12 form-group text-center">
                        <button type="button" class="btn green-dark" id="btnSearch">Search</button>
                    </div>
                </div>
                <div class="portlet-body dv_BugsReportContainer">
                    @Html.Action("_BugsList", "Bugs")
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#btnSearch").click(function () {
        var EmployeeId = $("#ddlEmployee").val();
        var ProjectId = $("#ddlProject").val();

        var model = {
            EmployeeId: EmployeeId,
            ProjectId: ProjectId
        }
        $.ajax({
            type: "GET",
            url: "/Bugs/_BugsList?UserId=" + EmployeeId + "&ProjectId=" + ProjectId,
            contentType: "application/text; charset=utf-8",
            dataType: "text",
            success: function (response) {
                $('.dv_BugsReportContainer').html(response);
                TableDatatablesFixedHeader.init();
            },
            failure: function (msg) {
                html = false;
            }
        });
    });
    function getParameterByName(name) {
        var url = window.location.href;
        name = name.replace(/[\[\]]/g, "\\$&");
        var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
            results = regex.exec(url);
        if (!results) return null;
        if (!results[2]) return '';
        return decodeURIComponent(results[2].replace(/\+/g, " "));
    }
</script>

TaskManagementOsvin/Views/Bugs/_BugsList.cshtml
@using TaskManagementOsvin.Security;
@using TaskManagementOsvin.Models;
@model List<BugsDomainModel>

<table class="table table-striped table-bordered table-hover table-header-fixed" id="sample_2">
    <thead>
        <tr class="">
            <th class="text-center"> Employee </th>
            <th class="text-center"> Department </th>
            <th class="text-center"> Project </th>
            <th class="text-center"> Subject </th>
            <th class="text-center"> Description </th>
            <th class="text-center"> Files </th>
            <th class="text-center"> Priority </th>
            <th class="text-center"> Status </th>
            <th class="text-center"> Feedback </th>
            @if (UserManager.user.roleType == roleTypeModel.Admin || UserManager.user.roleType == roleTypeModel.HR | UserManager.user.roleType == roleTypeModel.ProjectManager)
            {
                <th class="text-center"> Edit </th>
            }
            else
            {
                <th class="text-center"> Give Feedback </th>
            }
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var bug in Model)
            {
                <tr>
                    <td class="text-center"> @bug.EmployeeName </td>
                    <td class="text-center"> @bug.DepartmentName </td>
                    <td class="text-center"> @bug.ProjectTitle </td>
                    <td class="text-center"> @bug.BugSubject </td>
                    <td class="text-center"> @bug.BugDescription </td>
                    <td class="text-center"> @bug.Files </td>
                    <td class="text-center"> @bug.Priority </td>
                    <td class="text-center"> @bug.Status </td>
                    <td class="text-center"> @bug.EmployeeFeedBack </td>
                    @if (UserManager.user.roleType == roleTypeModel.Admin || UserManager.user.roleType == roleTypeModel.HR | UserManager.user.roleType == roleTypeModel.ProjectManager)
                    {
                        <td class="text-center"><a title="Edit" class="btn blue" href="~/Bugs/ReportBug?BugId=@bug.BugId"><i class="fa fa-edit"></i></a> </td>
                    }
                    else
                    {
                        <td class="text-center"><a title="Give Feedback" class="btn blue" href="javascript:;"><i class="fa fa-cogs"></i></a> </td>
                    }
                </tr>
            }
        }
    </tbody>
</table>