TaskManagementOsvin/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagementOsvin.Security;
using TaskManagementOsvin.Models;
using System.Net.Http;
using System.Net;
using System.Web.Script.Serialization;
using DomainModel.EntityModel;
using Providers.Helper;
using Newtonsoft.Json;
using System.IO;
using System.Globalization;
using System.Configuration;

namespace TaskManagementOsvin.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        string BaseURL = ConfigurationManager.AppSettings["BaseURL"];
        // GET: Project
        public ActionResult AddUpdateProject(int ProjectId = 0)
        {
            ViewBag.Class = "display-hide";
            GetProjectTypeAndClients();
            try
            {
                if (ProjectId > 0)
                {
                    var client = new HttpClient();
                    client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
                    var Clientresult = client.GetAsync(BaseURL + "/api/Project/GetProjectDetailsById?ProjectId=" + ProjectId).Result;
                    if (Clientresult.StatusCode == HttpStatusCode.OK)
                    {
                        var contents = Clientresult.Content.ReadAsStringAsync().Result;
                        var response = new JavaScriptSerializer().Deserialize<GetProjectByIdModel>(contents);
                        var a = string.IsNullOrEmpty(response.EstimateHours) ? (decimal?)null : Convert.ToDecimal(response.EstimateHours);
                        AddUpdateProjectModel model = new AddUpdateProjectModel()
                        {
                            ProjectId = response.ProjectId,
                            ClientId = response.ClientId,
                            ProjectTypeId = response.ProjectTypeId,
                            ProjectTitle = response.ProjectTitle,
                            ProjectUrl = response.ProjectUrl,
                            HourlyRate = response.HourlyRate,
                            FixedPrice=response.FixedPrice,
                            UploadDocument = response.UploadDocument,
                            StartDate = response.StartDate,
                            EndDate = response.EndDate,
                            EstimateHours = string.IsNullOrEmpty(response.EstimateHours) ? 0 : Convert.ToDecimal(response.EstimateHours),
                            AssignedHours = string.IsNullOrEmpty(response.AssignHours) ? (decimal?)null : Convert.ToDecimal(response.AssignHours),
                            developerCodinghours = string.IsNullOrEmpty(response.DeveloperCodingHours) ? (decimal?)null : Convert.ToDecimal(response.DeveloperCodingHours),
                            WebserviceHours = string.IsNullOrEmpty(response.WebServiceHours) ? (decimal?)null : Convert.ToDecimal(response.WebServiceHours),
                            EstimateDesignHours = string.IsNullOrEmpty(response.DesignHours) ? (decimal?)null : Convert.ToDecimal(response.DesignHours),
                            SEOHours = string.IsNullOrEmpty(response.SEOHours) ? (decimal?)null : Convert.ToDecimal(response.SEOHours),
                            MaintainenceHours = string.IsNullOrEmpty(response.MaintainenceHours) ? (decimal?)null : Convert.ToDecimal(response.MaintainenceHours),
                            NetworkSupportHours = string.IsNullOrEmpty(response.NetworkSupprotHours) ? (decimal?)null : Convert.ToDecimal(response.NetworkSupprotHours),
                            QualityAnalystHours = string.IsNullOrEmpty(response.QAHours) ? (decimal?)null : Convert.ToDecimal(response.QAHours),
                            UploadDetailsDocument = response.UploadDetailsDocument
                        };
                        return View(model);
                    }
                    else
                    {
                        ViewBag.Class = "alert-danger";
                        ViewBag.Message = "Error Occurred";
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Class = "alert-danger";
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        public ActionResult AddUpdateProject(AddUpdateProjectModel model)
        {
            ViewBag.Class = "alert-danger";
            ViewBag.Message = "Added Successfully";
            GetProjectTypeAndClients();
            try
            {
                if (ModelState.IsValid)
                {
                    model.CreatedBy = UserManager.user.UserId;
                    if (model.UploadDetailsDocumentFile != null && model.UploadDetailsDocumentFile.ContentLength > 0)
                    {
                        var uniqueName = Guid.NewGuid();
                        model.UploadDetailsDocument = uniqueName + model.UploadDetailsDocumentFile.FileName;
                        model.UploadDetailsDocumentFile.SaveAs(Server.MapPath("~/UploadDocuments/" + model.UploadDetailsDocument));
                        model.UploadDetailsDocumentFile = null; // do null nor it will cause error while serializing
                    }
                    if (model.UploadDocumentFile != null && model.UploadDocumentFile.ContentLength > 0)
                    {
                        var uniqueName = Guid.NewGuid();
                        model.UploadDocument = uniqueName + model.UploadDocumentFile.FileName;
                        model.UploadDocumentFile.SaveAs(Server.MapPath("~/UploadDocuments/" + model.UploadDocument));
                        model.UploadDocumentFile = null; // do null nor it will cause error while serializing
                    }
                    model.ProjectStatus = "Open";
                    model.Archived = "NonArchive";
                    var serialized = new JavaScriptSerializer().Serialize(model);
                    var client = new HttpClient();
                    var content = new StringContent(serialized, System.Text.Encoding.UTF8, "application/json");
                    client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
                    var Clientresult = client.PostAsync(BaseURL + "/api/Project/AddUpdateProject", content).Result;
                    if (Clientresult.StatusCode == HttpStatusCode.OK)
                    {
                        ViewBag.Class = "alert-success";
                        if (model.ProjectId > 0)
                        {
                            ViewBag.Message = "Updated Successfully";
                        }
                        var contents = Clientresult.Content.ReadAsStringAsync().Result;
                        var response = new JavaScriptSerializer().Deserialize<ResponseModel>(contents);
                        ModelState.Clear();
                    }
                    else if (Clientresult.StatusCode == HttpStatusCode.NotImplemented)
                    {
                        var contents = Clientresult.Content.ReadAsStringAsync().Result;
                        var response = new JavaScriptSerializer().Deserialize<ResponseModel>(contents);
                        ViewBag.Message = response.response;
                    }
                    else
                    {
                        ViewBag.Message = "Error Occurred";
                    }
                }
                else
                {
                    ViewBag.Message = "Error Occurred";
                }
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Error Occurred";
                return View();
            }
        }

        public ActionResult GetProfiles(long ProjectId = 0)
        {
            try
            {
                if (ProjectId > 0)
                {
                    var client = new HttpClient();
                    client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
                    var Clientresult = client.GetAsync(BaseURL + "/api/Profile/GetProfilesByProjectId/" + ProjectId).Result;
                    if (Clientresult.StatusCode == HttpStatusCode.OK)
                    {
                        var contents = Clientresult.Content.ReadAsStringAsync().Result;
                        var response = new JavaScriptSerializer().Deserialize<List<GetProfilesModel>>(contents);
                        return View(response);
                    }
                }
            }
            catch (Exception ex)
            {

            }
            return View();
        }

        //[HttpPost]
        //public ActionResult GetProfiles(AddUpdateUpworkProfileModel model)
        //{
        //    return View();
        //}

        public ActionResult AddUpdateProfile(long ProjectId = 0)
        {
            GetProjectTypeAndProjects();
            return View();
        }

        [HttpPost]
        public JsonResult AddUpdateProfile(List<UpdateUpworkProfileModel> ProfileList = null)
        {
            var result = "Successful <br />";
            try
            {
                if (ProfileList != null)
                {
                    ProfileList.ForEach(x => { x.createdBy = UserManager.user.UserId; });
                    var qs = Request.UrlReferrer.Query;
                    if (qs != "")
                    {
                        var ProjectId = Convert.ToUInt64(qs.Split('=')[1]);
                        if (ProjectId > 0)
                        {
                            var client = new HttpClient();
                            client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
                            var Clientresult = client.GetAsync(BaseURL + "/api/Profile/GetProfilesByProjectId/" + ProjectId).Result;
                            if (Clientresult.StatusCode == HttpStatusCode.OK)
                            {

TaskManagementOsvin/Views/Project/AddProjectAddendumDetails.cshtml
@using System.Configuration
@{
    ViewBag.Title = "AddProjectAddendumDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model TaskManagementOsvin.Models.AddendumModel
<div class="page-content">
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="~/Dashboard/Welcome">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="#">Add Project Addendums Details</a>
                <i class="fa fa-circle"></i>
            </li>
            @*<li>
                    <span>Page Layouts</span>
                </li>*@
        </ul>
        
    </div>
    <!-- END PAGE BAR -->
    <h1 class="page-title">
        Add Project Addendums Details
        <small></small>
    </h1>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered" id="form_wizard_1">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-layers font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">Add Project Addendums Details</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    @using (Html.BeginForm("AddProjectAddendumDetails", "Project", FormMethod.Post, new { enctype = "multipart/form-data", @id = "frmAddAddendum", @class = "form-horizontal" }))
                    {
                        <div class="form-body">
                            <div class="alert @ViewBag.AlertType @ViewBag.Class">
                                @*<button type="button" class="close" data-close="alert"></button>*@
                                <a class="close" onclick="$('.alert').hide()">×</a>
                                <span> @Html.ValidationMessage("CustomError") </span>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Project Name
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.DropDownListFor(m => m.ProjectId, ViewBag.listProjects as SelectList, "Select Project", new { @class = "form-control", @required = "required", @id = "ddlProject" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.ProjectId)
                                    </div>
                                    @*<input type="password" name="oldPassword" data-required="1" class="form-control" />*@
                                </div>
                            </div>
                           
                            <div class="form-group" id="dvHourlyRate" style="display:none">
                                <label class="control-label col-md-3">
                                    Hourly Rate  
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.HourlyRate, new { @class = "form-control", @placeholder = "Enter Hourly Rate like 0.00" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.HourlyRate)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Estimation Hours
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.EstimateHours, new { @class = "form-control", @required = "required", @placeholder = "Enter Hours" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.EstimateHours)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3">
                                   Assign Hours
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.AssignHours, new { @class = "form-control", @required = "required", @placeholder = "Enter Hours" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.AssignHours)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">Attach Addendums Documents</label>
                                <div class="col-md-6">
                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <div class="input-group input-large">
                                            <div class="form-control uneditable-input input-fixed input-medium" data-trigger="fileinput">
                                                <i class="fa fa-file fileinput-exists"></i>&nbsp;
                                                <span class="fileinput-filename"> </span>
                                            </div>
                                            <span class="input-group-addon btn default btn-file">
                                                <span class="fileinput-new"> Select file </span>
                                                <span class="fileinput-exists"> Change </span>
                                                @*<input type="file" name="...">*@
                                                @Html.TextBoxFor(m => m.UploadDocumentFile, new { type = "file" })
                                                <div class="text-danger">
                                                    @Html.ValidationMessageFor(m => m.UploadDocumentFile)
                                                    @Html.HiddenFor(m => m.UploadDocument)
                                                </div>
                                            </span>
                                            <a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput"> Remove </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Developer Coding Hours
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.DeveloperCodingHours, new { @class = "form-control", @placeholder = "Enter Hours" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.DeveloperCodingHours)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    WebService Design Hours
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.WebServiceHours, new { @class = "form-control", @placeholder = "Enter Hours" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.WebServiceHours)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Design Hours
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.DesignHours, new { @class = "form-control", @placeholder = "Enter Hours" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.DesignHours)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    QA Hours
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.QAHours, new { @class = "form-control", @placeholder = "Enter Hours" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.QAHours)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Is Approved
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.DropDownListFor(modelItem => modelItem.IsApprove, new[] { new SelectListItem { Text = "Please select", Value = "" }, new SelectListItem { Text = "True", Value = "True" }, new SelectListItem { Text = "False", Value = "False" } }, new { @class = "form-control", @required = "required", @id = "ddlStatus" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.IsApprove)
                                    </div>
                                    @*<input type="password" name="oldPassword" data-required="1" class="form-control" />*@
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button type="submit" class="btn green">Submit</button>
                                </div>
                            </div>
                        </div>
                    }
                    <!-- END FORM-->
                </div>
            </div>
            <!-- END VALIDATION STATES-->
        </div>
    </div>
</div>
<script type="text/javascript">
    var basehref = '@ConfigurationManager.AppSettings["BaseURL"]';
    $(document).ready(function () {
        ShowHideDivHourlyRate();
    });
    $(document).on('change', '#ddlProject', function (e) {
        //debugger
        ShowHideDivHourlyRate();
    });
    function ShowHideDivHourlyRate() {
        var ProjectId = $("#ddlProject").val();
        if (typeof ProjectId != 'undefined' && ProjectId != "") {
            var url = basehref + "/api/Project/GetProjectTypeById?ProjectId=" + ProjectId
            $.ajax({
                type: "GET",
                url: url,
                contentType: "application/json; charset=utf-8",
                dataType: "text",
                success: function (response) {
                    if (response == 4) {
                        $("#dvHourlyRate").hide();
                    }
                    else {
                        $("#dvHourlyRate").show();
                    }
                },
                failure: function (msg) {
                    console.log(error);
                }
            });
        }
    }
</script>

TaskManagementOsvin/Views/Project/AddWorkingHoursOfProjectBeforePMS.cshtml
@model TaskManagementOsvin.Models.ProjectWorkingHoursBeforePMSModel
@{
    ViewBag.Title = "AddWorkingHoursOfProjectBeforePMS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-content">
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="~/Dashboard/Welcome">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="#">Add Working Hours on Project Before PMS</a>
                <i class="fa fa-circle"></i>
            </li>
            @*<li>
                    <span>Page Layouts</span>
                </li>*@
        </ul>
        
    </div>
    <!-- END PAGE BAR -->
    <h1 class="page-title">
        Add Working Hours on Project Before PMS
        <small></small>
    </h1>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered" id="form_wizard_1">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-layers font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">Add Working Hours on Project Before PMS</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    @using (Html.BeginForm("AddWorkingHoursOfProjectBeforePMS", "Project", FormMethod.Post, new { enctype = "multipart/form-data", @id = "frmAddWorkingHours", @class = "form-horizontal" }))
                    {
                        <div class="form-body">
                            <div class="alert @ViewBag.AlertType @ViewBag.Class">
                                @*<button type="button" class="close" data-close="alert"></button>*@
                                <a class="close" onclick="$('.alert').hide()">×</a>
                                <span> @Html.ValidationMessage("CustomError") </span>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                   Project Title
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.DropDownListFor(m => m.ProjectId, ViewBag.listProjects as SelectList, "Select Project", new { @class = "form-control", @required = "required" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.ProjectId)
                                    </div>
                                    @*<input type="password" name="oldPassword" data-required="1" class="form-control" />*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Estimate Working Hours Before PMS
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.WorkinghHours, new {@class = "form-control", @required = "required", @placeholder="Enter Hours" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.WorkinghHours)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>                          
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button type="submit" class="btn green">Submit</button>
                                </div>
                            </div>
                        </div>
                    }
                    <!-- END FORM-->
                </div>
            </div>
            <!-- END VALIDATION STATES-->
        </div>
    </div>
</div>

TaskManagementOsvin/Views/Project/GetProfiles.cshtml
@{
    ViewBag.Title = "GetProfiles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<TaskManagementOsvin.Models.GetProfilesModel>
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="javascript:">Profile List</a>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h1 class="page-title">
        Project List
    </h1>
    <!-- END PAGE TITLE-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-social-dribbble font-green"></i>
                        <span class="caption-subject font-green bold uppercase">Profile List</span>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover table-header-fixed" id="sample_2">
                    <thead>
                        <tr>
                            <th>Profile Name</th>
                            <th>Total Amount</th>
                            <th>Hourly Rate</th>
                            <th>Logged Hours</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Count() > 0)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ProfileName</td>
                                    <td>@item.TotalAmount</td>
                                    <td>@item.HourlyRate</td>
                                    <td>@item.TotalAmount</td>
                                    <td><a href="@Url.Action("AddUpdateProfile","Project",new { ProjectId= item.ProjectId })">Edit</a></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

TaskManagementOsvin/Views/Project/ProjectList.cshtml
@{
    ViewBag.Title = "ProjectList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="javascript:">Project Details</a>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h1 class="page-title">
        Project Details
    </h1>
    <!-- END PAGE TITLE-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-body" id="update">
                    @Html.Action("_ProjectList")
                </div>
            </div>
        </div>
    </div>
</div>