TaskManagementOsvin/Models/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TaskManagementOsvin.Models
{   
        public class ChangePasswordReqModel
        {
            public long UserId { get; set; }
            [Required(ErrorMessage = "This field is required.")]
            public string OldPassword { get; set; }
            [Required(ErrorMessage = "This field is required.")]
            public string NewPassword { get; set; }
            [Compare("NewPassword", ErrorMessage = "Password did not match")]
            public string ConfirmPassword { get; set; }
        }
}

TaskManagementOsvin/Controllers/DashboardController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TaskManagementOsvin.Models;
using TaskManagementOsvin.Security;

namespace TaskManagementOsvin.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        string BaseURL = ConfigurationManager.AppSettings["BaseURL"];
        // GET: Dashboard
        //static GetDSRModel GetDSRModel = new GetDSRModel() { startdate = DateTime.Now.AddDays(-48).ToString("dd/MM/yyyy"), enddate = DateTime.Now.AddDays(-40).ToString("dd/MM/yyyy") };
        static GetDSRModel GetDSRModel = new GetDSRModel() { startdate = DateTime.Now.AddDays(-(int)DateTime.Today.DayOfWeek + (int)DayOfWeek.Sunday).ToString("dd/MM/yyyy"), enddate = DateTime.Now.AddDays(-(int)DateTime.Today.DayOfWeek + (int)DayOfWeek.Saturday).ToString("dd/MM/yyyy") };
        public ActionResult Welcome()
        {
            return View(GetDSRModel);
        }

        [HttpPost]
        public ActionResult Welcome(GetDSRModel Dsrmodel)
        {
            GetDSRModel.startdate = DateTime.ParseExact(Dsrmodel.startdate, "dd/MM/yyyy", null).ToString("dd/MM/yyyy");
            GetDSRModel.enddate = DateTime.ParseExact(Dsrmodel.enddate, "dd/MM/yyyy", null).ToString("dd/MM/yyyy");
            return View(GetDSRModel);
        }
        [CustomAuthorize(roles: "HR,Admin,Team Leader,Project Manager")]
        public PartialViewResult _projectReport()
        {
            decimal weekTotal = 0, OverallTotal = 0;
            var reports = GetProjectReport(GetDSRModel);
            if (UserManager.user.roleType == roleTypeModel.TeamLeader && reports.dsr != null && reports.dsr.Count() > 0)
            {
                reports.dsr = reports.dsr.Where(x => x.DepartmentId == UserManager.user.DepartmentId).ToList();
            }
            foreach (var item in reports.dsr)
            {
                weekTotal += ConversionInMinute(item.WorkingHoursOfProject);
            }
            foreach (var workingHours in reports.dsr)
            {
                OverallTotal += ConversionInMinute(workingHours.TotalWorkingHoursOfProject);
            }
            reports.OverallTotalWorkingHours = ConversionInHour(weekTotal);
            reports.OverallWeekTotalWorkingHours = ConversionInHour(OverallTotal);
            return PartialView(reports);
        }
        [CustomAuthorize(roles: "HR,Admin,Team Leader,Project Manager")]
        public PartialViewResult _employeeReport()
        {
            decimal TotalWeekelyWorkingHours = 0;
            List<WeekelyEmployeeReportModel> EmployeeReports = new List<WeekelyEmployeeReportModel>(); 
            var client = new HttpClient();
            var serialized = new JavaScriptSerializer().Serialize(GetDSRModel);
            var content = new StringContent(serialized, Encoding.UTF8, "application/json");
            client.BaseAddress = new Uri(HttpContext.Request.Url.AbsoluteUri);
            var result = client.PostAsync(BaseURL + "/api/Employee/GetWeekelySummaryOfEmpDetails", content).Result;
            if (result.StatusCode == HttpStatusCode.OK)
            {
                var contents = result.Content.ReadAsStringAsync().Result;
                var reports = new JavaScriptSerializer().Deserialize<List<GetWeekelySummaryOfEmpModel>>(contents);
                if (UserManager.user.roleType == roleTypeModel.TeamLeader)
                {
                    reports = reports.Where(x => x.DepartmentId == UserManager.user.DepartmentId).ToList();
                }
                var GroupedReports = reports.GroupBy(x => x.EmployeeId).ToList();
                foreach (var item in GroupedReports)
                {
                    var empId = item.FirstOrDefault().EmployeeId;
                    var GetEmpReport = reports.Where(x => x.EmployeeId == empId).ToList();
                    var MondayReports = GetEmpReport.Where(x => x.CreatedDate.DayOfWeek == DayOfWeek.Monday).ToList();
                    var TuesdayReports = GetEmpReport.Where(x => x.CreatedDate.DayOfWeek == DayOfWeek.Tuesday).ToList();
                    var WednesdayReports = GetEmpReport.Where(x => x.CreatedDate.DayOfWeek == DayOfWeek.Wednesday).ToList();
                    var ThursdayReports = GetEmpReport.Where(x => x.CreatedDate.DayOfWeek == DayOfWeek.Thursday).ToList();
                    var FridayReports = GetEmpReport.Where(x => x.CreatedDate.DayOfWeek == DayOfWeek.Friday ).ToList();
                    var SaturdayReports = GetEmpReport.Where(x => x.CreatedDate.DayOfWeek == DayOfWeek.Saturday).ToList();
                    var SundayReports = GetEmpReport.Where(x => x.CreatedDate.DayOfWeek == DayOfWeek.Sunday).ToList();
                    if (MondayReports.Count() > 0)
                    {
                        decimal mins = 0;
                        foreach (var report in MondayReports)
                        {
                            mins += ConversionInMinute(report.WorkingHours);
                        }
                        var ReportModel = new WeekelyEmployeeReportModel()
                        {
                            EmployeeId = item.FirstOrDefault().EmployeeId,
                            DepartmentName = item.FirstOrDefault().DepartmentName,
                            Name = item.FirstOrDefault().Name,
                            ProjectTitle = item.FirstOrDefault().ProjectTitle,
                            WorkingHours = ConversionInHour(mins),
                            DayOfWeek = DayOfWeek.Monday
                        };
                        EmployeeReports.Add(ReportModel);
                        var totalWeekelyMins = ConversionInMinute(TotalWeekelyWorkingHours.ToString()) + mins;
                        TotalWeekelyWorkingHours = ConversionInHour(totalWeekelyMins);
                    }
                    if (TuesdayReports.Count() > 0)
                    {
                        decimal mins = 0;
                        foreach (var report in TuesdayReports)
                        {
                            mins += ConversionInMinute(report.WorkingHours);
                        }
                        var ReportModel = new WeekelyEmployeeReportModel()
                        {
                            EmployeeId = item.FirstOrDefault().EmployeeId,
                            DepartmentName = item.FirstOrDefault().DepartmentName,
                            Name = item.FirstOrDefault().Name,
                            ProjectTitle = item.FirstOrDefault().ProjectTitle,
                            WorkingHours = ConversionInHour(mins),
                            DayOfWeek = DayOfWeek.Tuesday
                        };
                        EmployeeReports.Add(ReportModel);
                        var totalWeekelyMins = ConversionInMinute(TotalWeekelyWorkingHours.ToString()) + mins;
                        TotalWeekelyWorkingHours = ConversionInHour(totalWeekelyMins);
                    }
                    if (WednesdayReports.Count() > 0)
                    {
                        decimal mins = 0;
                        foreach (var report in WednesdayReports)
                        {
                            mins += ConversionInMinute(report.WorkingHours);
                        }
                        var ReportModel = new WeekelyEmployeeReportModel()
                        {
                            EmployeeId = item.FirstOrDefault().EmployeeId,
                            DepartmentName = item.FirstOrDefault().DepartmentName,
                            Name = item.FirstOrDefault().Name,
                            ProjectTitle = item.FirstOrDefault().ProjectTitle,
                            WorkingHours = ConversionInHour(mins),
                            DayOfWeek = DayOfWeek.Wednesday
                        };
                        EmployeeReports.Add(ReportModel);
                        var totalWeekelyMins = ConversionInMinute(TotalWeekelyWorkingHours.ToString()) + mins;
                        TotalWeekelyWorkingHours = ConversionInHour(totalWeekelyMins);
                    }
                    if (ThursdayReports.Count() > 0)
                    {
                        decimal mins = 0;
                        foreach (var report in ThursdayReports)
                        {
                            mins += ConversionInMinute(report.WorkingHours);
                        }
                        var ReportModel = new WeekelyEmployeeReportModel()
                        {
                            EmployeeId = item.FirstOrDefault().EmployeeId,
                            DepartmentName = item.FirstOrDefault().DepartmentName,
                            Name = item.FirstOrDefault().Name,
                            ProjectTitle = item.FirstOrDefault().ProjectTitle,
                            WorkingHours = ConversionInHour(mins),
                            DayOfWeek = DayOfWeek.Thursday
                        };
                        EmployeeReports.Add(ReportModel);
                        var totalWeekelyMins = ConversionInMinute(TotalWeekelyWorkingHours.ToString()) + mins;
                        TotalWeekelyWorkingHours = ConversionInHour(totalWeekelyMins);
                    }
                    if (FridayReports.Count() > 0)
                    {
                        decimal mins = 0;
                        foreach (var report in FridayReports)
                        {
                            mins += ConversionInMinute(report.WorkingHours);
                        }
                        var ReportModel = new WeekelyEmployeeReportModel()
                        {
                            EmployeeId = item.FirstOrDefault().EmployeeId,
                            DepartmentName = item.FirstOrDefault().DepartmentName,

TaskManagementOsvin/Views/Dashboard/ChangePassword.cshtml
@model TaskManagementOsvin.Models.ChangePasswordReqModel
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-content">
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="~/Dashboard/Welcome">Dashboard</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="#">Change Password</a>
                <i class="fa fa-circle"></i>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <h1 class="page-title">
        Change Password
        <small></small>
    </h1>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered" id="form_wizard_1">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-layers font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">Change Password</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    @using (Html.BeginForm("ChangePassword", "Dashboard", FormMethod.Post, new { enctype = "multipart/form-data", @id = "frmChangePassword", @class = "form-horizontal" }))
                    {
                        <div class="form-body">
                            <div class="alert @ViewBag.AlertType @ViewBag.Class">
                                @*<button type="button" class="close" data-close="alert"></button>*@
                                <a class="close" onclick="$('.alert').hide()">×</a>
                                <span> @Html.ValidationMessage("CustomError") </span>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Old Password
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.OldPassword, new { @type = "password", @class = "form-control" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.OldPassword)
                                    </div>
                                    @*<input type="password" name="oldPassword" data-required="1" class="form-control" />*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    New Password
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.NewPassword, new { @type = "password", @class = "form-control" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.NewPassword)
                                    </div>
                                    @*<input name="newPasswprd" type="text" class="form-control" />*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Confirm New Password
                                    <span class="required"> * </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.TextBoxFor(m => m.ConfirmPassword, new { @type = "password", @class = "form-control" })
                                    <div class="text-danger">
                                        @Html.ValidationMessageFor(m => m.ConfirmPassword)
                                    </div>
                                    @*<input name="confirmPassword" type="text" class="form-control" />*@
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button type="submit" class="btn green">Submit</button>
                                </div>
                            </div>
                        </div>
                    }
                    <!-- END FORM-->
                </div>
            </div>
            <!-- END VALIDATION STATES-->
        </div>
    </div>
</div>

TaskManagementOsvin/Views/Dashboard/FullProjectReport.cshtml
@{
    ViewBag.Title = "FullProjectReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="javascript:">Full Project Report</a>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h1 class="page-title">
        Full Project Report
    </h1>
    <!-- END PAGE TITLE-->
    <!-- END PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                @Html.Raw(ViewBag.Table)
            </div>
        </div>
    </div>
</div>
<style>
    .fixed-header{
  top:50px;
  position:fixed;
  width:auto;
  display:none;
  border:none;
  background-color:white;
}
    .fixed-footer{
  bottom:0;
  position:fixed;
  width:auto;
  display:table;
  border:none;
  background-color:white;
  margin-bottom:0;
}
</style>
<script>
    (function ($) {
        $.fn.fixMe = function () {
            return this.each(function () {
                var $this = $(this),
                   $t_fixed,$t_foot
                function init() {
                    $this.wrap('<div/>');
                    $t_fixed = $this.clone();
                    $t_foot = $this.clone();
                    $t_fixed.find("tbody,tfoot").remove().end().addClass("fixed-header").insertBefore($this);
                    $t_foot.find("tbody,thead").remove().end().addClass("fixed-footer").insertAfter($this);
                    resizeFixed();
                }
                function resizeFixed() {
                    $t_fixed.find("th").each(function (index) {
                        $(this).css("width", $this.find("th").eq(index).outerWidth() + "px");
                    });
                    $t_foot.find("th").each(function (index) {
                        $(this).css("width", $this.find("tfoot th").eq(index).outerWidth() + "px");
                    });
                }
                function scrollFixed() {
                    var offset = $(this).scrollTop(),
                    tableOffsetTop = $this.offset().top,
                    tableOffsetBottom = tableOffsetTop + $this.height() - $this.find("thead").height();
                    tableOffsetBottomTfoot = tableOffsetTop + $this.height() - $this.find("tfoot").height();
                    if (offset >= tableOffsetTop && offset > tableOffsetBottomTfoot)
                        $t_foot.hide();
                    else if (offset <= tableOffsetBottomTfoot && $t_foot.is(":hidden"))
                        $t_foot.show();

                    if (offset < tableOffsetTop || offset > tableOffsetBottom)
                        $t_fixed.hide();
                    else if (offset >= tableOffsetTop && offset <= tableOffsetBottom && $t_fixed.is(":hidden"))
                        $t_fixed.show();
                }
                $(window).resize(resizeFixed);
                $(window).scroll(scrollFixed);
                init();
            });
        };
    })(jQuery);
</script>
<script>
    $(window).load(function () {
        $("table").fixMe();
    })
</script>

TaskManagementOsvin/Views/Dashboard/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //var action = "";
    //var disabled = "";
}
@using TaskManagementOsvin.Security;
@using TaskManagementOsvin.Models;
@model GetDSRModel
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="javascript:">Dashboard</a>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h4 class="page-header">
        Welcome <b>@UserManager.user.FirstName @UserManager.user.LastName</b>
    </h4>
    <!-- END PAGE TITLE-->
    @if (UserManager.user.roleType == roleTypeModel.Admin || UserManager.user.roleType == roleTypeModel.HR || UserManager.user.roleType == roleTypeModel.TeamLeader)
    {
        <div class="row">
            <div class="col-md-12">
                <div class="m-heading-1 border-green m-bordered">
                    <h3 class="text-center">
                        Summary Of Week Start Date : <span class="label label-info">@DateTime.ParseExact(Model.startdate, "dd/MM/yyyy", null).ToString("dd-MMMM-yyyy")</span>
                        End Date  <span class="label label-info">@DateTime.ParseExact(Model.enddate, "dd/MM/yyyy", null).ToString("dd-MMMM-yyyy")</span>
                    </h3>
                    @using (Html.BeginForm())
                {
                        <div class="col-md-4" style="padding-left:0">
                            <div class="input-group input-large datepicker input-daterange" data-date-format="dd/mm/yyyy">
                                @Html.TextBoxFor(x => x.startdate, new { @class = "form-control", @name = "from" })
                                <span class="input-group-addon"> to </span>
                                @Html.TextBoxFor(x => x.enddate, new { @class = "form-control", @name = "to" })
                            </div>
                        </div>
                        <div class="col-md-4" style="padding-left:0;padding-top:5px">
                            <input type="submit" value="Submit" class="btn btn-success" />
                        </div>
                    }
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    @Html.Action("_projectReport")
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    @Html.Action("_employeeReport")
                </div>
            </div>
        </div>
    }
</div>

TaskManagementOsvin/Views/Dashboard/_employeeReport.cshtml
@using TaskManagementOsvin.Models;
@model List<WeekelyEmployeeReportModel> 
@using TaskManagementOsvin.Controllers
@{ 
    DashboardController dc = new DashboardController();
    decimal TotalWorkingMinsOfMon = 0, TotalWorkingMinsOfTue = 0, TotalWorkingMinsOfWed = 0, TotalWorkingMinsOfThu = 0, TotalWorkingMinsOfFri = 0, TotalWorkingMinsOfSat = 0, TotalWorkingMinsOfSun = 0, OverallTotalWorkinginMins = 0;
}
<!-- BEGIN EXAMPLE TABLE PORTLET-->
<div class="portlet-title">
    <div class="caption">
        <i class="icon-settings font-red"></i>
        <span class="caption-subject font-red sbold uppercase">Employee week report</span>
    </div>
</div>
<div class="portlet-body">
    <table class="table table-striped table-bordered table-hover table-header-fixed nosort-table">
        <thead>
            <tr>
                <th> Department </th>
                <th> Employee </th>
                <th> Mon </th>
                <th> Tue </th>
                <th> Wed </th>
                <th> Thur </th>
                <th> Fri </th>
                <th> Sat </th>
                <th> Sun </th>
                <th>Total</th>
            </tr>
        </thead>
        @if (Model != null && Model.Count() > 0)
        {
            <tbody>
                @foreach (var item in Model.GroupBy(x => x.EmployeeId))
                {
                    decimal TotalWorkingHoursInMins = 0;
                    var MonWorkingHours = Model.FirstOrDefault(x => x.DayOfWeek == DayOfWeek.Monday && x.EmployeeId == item.FirstOrDefault().EmployeeId);
                    var TueWorkingHours = Model.FirstOrDefault(x => x.DayOfWeek == DayOfWeek.Tuesday && x.EmployeeId == item.FirstOrDefault().EmployeeId);
                    var WedWorkingHours = Model.FirstOrDefault(x => x.DayOfWeek == DayOfWeek.Wednesday && x.EmployeeId == item.FirstOrDefault().EmployeeId);
                    var ThuWorkingHours = Model.FirstOrDefault(x => x.DayOfWeek == DayOfWeek.Thursday && x.EmployeeId == item.FirstOrDefault().EmployeeId);
                    var FriWorkingHours = Model.FirstOrDefault(x => x.DayOfWeek == DayOfWeek.Friday && x.EmployeeId == item.FirstOrDefault().EmployeeId);
                    var SatWorkingHours = Model.FirstOrDefault(x => x.DayOfWeek == DayOfWeek.Saturday && x.EmployeeId == item.FirstOrDefault().EmployeeId);
                    var SunWorkingHours = Model.FirstOrDefault(x => x.DayOfWeek == DayOfWeek.Sunday && x.EmployeeId == item.FirstOrDefault().EmployeeId);

                    var MondayMins = dc.ConversionInMinute((MonWorkingHours != null ? MonWorkingHours.WorkingHours : 0).ToString());
                    TotalWorkingMinsOfMon = MondayMins + TotalWorkingMinsOfMon;

                    var TuesdayMins = dc.ConversionInMinute((TueWorkingHours != null ? TueWorkingHours.WorkingHours : 0).ToString());
                    TotalWorkingMinsOfTue = TuesdayMins + TotalWorkingMinsOfTue;

                    var WednesdayMins = dc.ConversionInMinute((WedWorkingHours != null ? WedWorkingHours.WorkingHours : 0).ToString());
                    TotalWorkingMinsOfWed = WednesdayMins + TotalWorkingMinsOfWed;

                    var ThursdayMins = dc.ConversionInMinute((ThuWorkingHours != null ? ThuWorkingHours.WorkingHours : 0).ToString());
                    TotalWorkingMinsOfThu = ThursdayMins + TotalWorkingMinsOfThu;

                    var FridayMins = dc.ConversionInMinute((FriWorkingHours != null ? FriWorkingHours.WorkingHours : 0).ToString());
                    TotalWorkingMinsOfFri = FridayMins + TotalWorkingMinsOfFri;

                    var SaturdayMins = dc.ConversionInMinute((SatWorkingHours != null ? SatWorkingHours.WorkingHours : 0).ToString());
                    TotalWorkingMinsOfSat = SaturdayMins + TotalWorkingMinsOfSat;

                    var SundayMins = dc.ConversionInMinute((SunWorkingHours != null ? SunWorkingHours.WorkingHours : 0).ToString());
                    TotalWorkingMinsOfSun = SundayMins + TotalWorkingMinsOfSun;


                    TotalWorkingHoursInMins = MondayMins + TotalWorkingHoursInMins;
                    TotalWorkingHoursInMins = TuesdayMins + TotalWorkingHoursInMins;
                    TotalWorkingHoursInMins = WednesdayMins + TotalWorkingHoursInMins;
                    TotalWorkingHoursInMins = ThursdayMins + TotalWorkingHoursInMins;
                    TotalWorkingHoursInMins = FridayMins + TotalWorkingHoursInMins;
                    TotalWorkingHoursInMins = SaturdayMins + TotalWorkingHoursInMins;
                    TotalWorkingHoursInMins = SundayMins + TotalWorkingHoursInMins;
                    OverallTotalWorkinginMins += TotalWorkingHoursInMins;
                    <tr>
                        <td>@item.FirstOrDefault().DepartmentName</td>
                        <td>@item.FirstOrDefault().Name</td>
                        <td>@(MonWorkingHours != null ? MonWorkingHours.WorkingHours : 0)</td>
                        <td>@(TueWorkingHours != null ? TueWorkingHours.WorkingHours : 0)</td>
                        <td>@(WedWorkingHours != null ? WedWorkingHours.WorkingHours : 0)</td>
                        <td>@(ThuWorkingHours != null ? ThuWorkingHours.WorkingHours : 0)</td>
                        <td>@(FriWorkingHours != null ? FriWorkingHours.WorkingHours : 0)</td>
                        <td>@(SatWorkingHours != null ? SatWorkingHours.WorkingHours : 0)</td>
                        <td>@(SunWorkingHours != null ? SunWorkingHours.WorkingHours : 0)</td>
                        <td>@dc.ConversionInHour(TotalWorkingHoursInMins)</td>
                    </tr>
                }
                
            </tbody>
            <tfoot>
                <tr>
                    <th></th>
                    <th></th>
                    <th><span>@dc.ConversionInHour(TotalWorkingMinsOfMon)</span></th>
                    <th><span>@dc.ConversionInHour(TotalWorkingMinsOfTue)</span></th>
                    <th><span>@dc.ConversionInHour(TotalWorkingMinsOfWed)</span></th>
                    <th><span>@dc.ConversionInHour(TotalWorkingMinsOfThu)</span></th>
                    <th><span>@dc.ConversionInHour(TotalWorkingMinsOfFri)</span></th>
                    <th><span>@dc.ConversionInHour(TotalWorkingMinsOfSat)</span></th>
                    <th><span>@dc.ConversionInHour(TotalWorkingMinsOfSun)</span></th>
                    <th><span>@dc.ConversionInHour(OverallTotalWorkinginMins)</span></th>
                </tr>
           </tfoot>
        }
    </table>
</div>
<!-- END EXAMPLE TABLE PORTLET-->